In [14]:
import tensorflow as tf

In [15]:
import numpy as np

In [16]:
a=[]
for i in range(10):
    tmp=np.zeros([28,28,3])+i
    a.append(tmp)
a=np.array(a)
print(np.shape(a))
img=tf.constant(a)
sess=tf.Session()

    
    
    
    

(10, 28, 28, 3)


In [17]:
#索引
t1=img[1,:,:,:]
print(sess.run(t1))


[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 ...

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [18]:
#切片
t2=tf.slice(img,[1,0,0,0],[1,28,28,3])
print(sess.run(t2))


[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  ...

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]


In [19]:
#取第1,3,5,7张照片
t3=img[0:8:2,:,:,:]
print(sess.run(t3))


[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[2. 2. 2.]
   [2. 2. 2.]
   [2. 2. 2.]
   ...
   [2. 2. 2.]
   [2. 2. 2.]
   [2. 2. 2.]]

  [[2. 2. 2.]
   [2. 2. 2.]
   [2. 2. 2.]
   ...
   [2. 2. 2.]
   [2. 2. 2.]
   [2. 2. 2.]]

  [[2. 2. 2.]
   [2. 2. 2.]
   [2. 2. 2.]
   ...
   [2. 2. 2.]
   [2. 2. 2.]
   [2. 2. 2.]]

  ...

  [[2. 2. 2.]
   [2. 2. 2.]
   [2. 2. 2.]
   ...
   [2. 2. 2.]
   [2. 2. 2.]
   [2. 2. 2.]]

  [[2. 2. 2.]
   [2. 2. 2.]
   [2. 2. 2.]
   ...
   [2

In [11]:
#取6-8张中心部分
t4=img[6:8,7:14,7:14,:]
print(sess.run(t4))


[[[[6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]]

  [[6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]]

  [[6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]]

  [[6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]]

  [[6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]]

  [[6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]]

  [[6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]]]


 [[[7. 7. 7.]
   [7. 7. 7.]
   [7. 7. 7.]
   [7. 7. 7.]
   [7. 7. 7.]
   [7. 7. 7.]
   [7. 7. 7.]]

  [[7. 7. 7.]
   [7. 7. 7.]
   [7. 7. 7.]
   [7. 7. 7.]
   [7. 7. 7.]
   [7. 7. 7.]
   [7. 7. 7.]]

  [[7. 7. 7.]
   [7. 7. 7.]
   [7. 7. 7.]
   [7. 7. 7.]
   [7. 7. 7.]
   [7. 7. 7.]
   [7. 7. 7.]]

In [20]:
#将图片拆成三份单通道图片
t5,t6,t7=tf.split(img,[1,1,1],3)
print(sess.run(t5))
print(sess.run(t6))
print(sess.run(t7))
print(sess.run(t1))
  

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  ...

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]]


 [[[2.]
   [2.]
   [2.]
   ...
   [2.]
   [2.]
   [2.]]

  [[2.]
   [2.]
   [2.]
   ...
   [2.]
   [2.]
   [2.]]

  [[2.]
   [2.]
   [2.]
   ...
   [2.]
   [2.]
   [2.]]

  ...

  [[2.]
   [2.]
   [2.]
   ...
   [2.]
   [2.]
   [2.]]

  [[2.]
   [2.]
   [2.]
   ...
   [2.]
   [2.]
   [2.]]

  [[2.

In [21]:
#输出图片的张量的阶和shape
print(sess.run(tf.rank(img)))
print(img.shape)  

4
(10, 28, 28, 3)
